#!/usr/bin/perl

use strict;
use warnings;

use Client;
use Body;
use Empire;

print "Starting...\n\n";

my $c = Client->load( 'conf' );
my $empire = Empire->get_mine($c);

print "\n"x4 ,"Empire: ", $empire->name, "\n";

my $home = $empire->home_planet();
my $star = $home->star;

printf "Home Planet: %s at orbit %0d of %s\n", $home->name, $home->orbit, $star->name;


my %activity;

my @bodies;
for my $b ( $empire->planets ) {

    printf "%20s %s\n", $b->name, $b->location;
    print join "\n", $b->food, $b->energy, $b->ore, $b->water, $b->waste, $b->happiness, "";


}


