#!/usr/bin/perl

use strict;
use warnings;

use Client;
use Body;

print "Starting...\n\n";

my $c = Client->load( 'conf' );
my $es = $c->get_empire_status;


my %activity;

my @bodies;
for my $p_id ( $es->planets ) {
    warn "===============> Checking Planet $p_id\n";

    my $b = Body->new_from_id( $c, $p_id );

    push @bodies, $b;
}

for my $b ( @bodies ) {

    printf "%20s %s\n", $b->name, $b->location;
    print join "\n", $b->food, $b->energy, $b->ore, $b->water, $b->waste, $b->happiness, "";


}


